name: build-and-test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: install code
        uses: actions/checkout@v4

      - name: build code
        run: echo building the kernel

      - name: test code
        run: echo testing the kernel

      - name: return error
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('test to return an error')
